twig:
    default_path: '%kernel.project_dir%/templates'
    
    globals:
        assets: 'public/assets'
        front: 'public/assets/front'
        css: 'public/assets/front/css'

when@test:
    twig:
        strict_variables: true
